name: build test release

on:
  push:
    branches:
      - master

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
          server-id: github

      - name: View java
        run: ls /usr/lib/jvm

      - name: Build and Release
        uses: qcastel/github-actions-maven-release@v1.12.39
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITREPO_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
        with:
          version-minor: true
          release-branch-name: "master"
          git-release-bot-name: "release-bot"
          git-release-bot-email: "hronom@gmail.com"
